#!/bin/bash

debianversionname=$(lsb_release -a | grep Codename | awk -F' ' '{print  $2}')

sudo service tomcat7 stop

appversion=$(cat upstream_version)
echo "Downloading subsonic $appversion..."
sudo wget -O ../subsonic.zip http://downloads.sourceforge.net/project/subsonic/subsonic/$appversion/subsonic-${appversion}-war.zip > /dev/null 2>&1
echo "Extracting to $final_path..."
mkdir -p ../subsonic
sudo unzip ../subsonic.zip -d ../subsonic  > /dev/null 2>&1

sudo rm -rf /var/lib/tomcat7/webapps/subsonic/
sudo cp ../subsonic/*.war /var/lib/tomcat7/webapps/subsonic.war

sudo chown -R tomcat7:tomcat7 /var/lib/tomcat7/webapps/
sudo service tomcat7 start
